
import React from 'react';
import { 
  Sprout, 
  GraduationCap, 
  HeartPulse, 
  Briefcase, 
  Baby, 
  Store,
  Home,
  Wallet,
  Zap
} from 'lucide-react';
import { Scheme, SchemeCategory } from './types';

export const INDIAN_STATES_UTS = [
  "Andaman and Nicobar Islands", "Andhra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", 
  "Chandigarh", "Chhattisgarh", "Dadra and Nagar Haveli and Daman and Diu", "Delhi", "Goa", 
  "Gujarat", "Haryana", "Himachal Pradesh", "Jammu and Kashmir", "Jharkhand", "Karnataka", 
  "Kerala", "Ladakh", "Lakshadweep", "Madhya Pradesh", "Maharashtra", "Manipur", 
  "Meghalaya", "Mizoram", "Nagaland", "Odisha", "Puducherry", "Punjab", "Rajasthan", 
  "Sikkim", "Tamil Nadu", "Telangana", "Tripura", "Uttar Pradesh", "Uttarakhand", "West Bengal"
];

export const OCCUPATIONS = [
  "Farmer",
  "Student",
  "Self-employed / Small Business",
  "Salaried Employee (Private)",
  "Government Employee",
  "Unemployed",
  "Retired / Senior Citizen",
  "Homemaker",
  "Daily Wage Laborer",
  "Artisan / Handicraft Worker",
  "Other"
];

export const CATEGORIES: { label: SchemeCategory | 'Energy'; icon: React.ReactNode; color: string }[] = [
  { label: 'Agriculture', icon: <Sprout size={24} />, color: 'bg-green-100 text-green-700' },
  { label: 'Education', icon: <GraduationCap size={24} />, color: 'bg-blue-100 text-blue-700' },
  { label: 'Health', icon: <HeartPulse size={24} />, color: 'bg-red-100 text-red-700' },
  { label: 'Employment', icon: <Briefcase size={24} />, color: 'bg-purple-100 text-purple-700' },
  { label: 'Women & Child', icon: <Baby size={24} />, color: 'bg-pink-100 text-pink-700' },
  { label: 'Business', icon: <Store size={24} />, color: 'bg-indigo-100 text-indigo-700' },
  { label: 'Housing', icon: <Home size={24} />, color: 'bg-orange-100 text-orange-700' },
  { label: 'Finance', icon: <Wallet size={24} />, color: 'bg-teal-100 text-teal-700' },
];

export const MOCK_SCHEMES: Scheme[] = [
  // --- CENTRAL SCHEMES ---
  {
    id: 'pm-surya-ghar',
    title: 'PM Surya Ghar: Muft Bijli Yojana (2025)',
    description: 'Providing free electricity up to 300 units per month to 1 crore households through rooftop solar installations with massive subsidies.',
    category: 'Housing',
    level: 'Central',
    ministry: 'Ministry of New and Renewable Energy',
    updatedAt: '15 Jan 2025',
    expiryDate: '2027-12-31',
    objectives: ['Provide free electricity up to 300 units.', 'Promote sustainable energy.', 'Reduce utility bills.'],
    benefits: ['Subsidy up to ₹78,000.', 'Free power units.', 'Income from surplus power.'],
    eligibility: ['Indian citizen.', 'Roof ownership.', 'Valid electricity connection.'],
    documents: ['Aadhaar', 'Electricity Bill', 'Bank Passbook'],
    howToApply: [
      '1. Visit pmsuryaghar.gov.in and click "Apply for Rooftop Solar".',
      '2. Register with your Consumer ID and DISCOM name.',
      '3. Submit application for technical feasibility approval.',
      '4. Install the solar plant through an empanelled vendor.',
      '5. Apply for net-metering and inspection to receive subsidy.'
    ],
    applicationUrl: 'https://pmsuryaghar.gov.in/',
    faqs: [{ question: 'What is the maximum subsidy?', answer: 'For a 3kW system, the subsidy is ₹78,000.' }]
  },
  {
    id: 'pm-vidyalaxmi',
    title: 'PM-Vidyalaxmi Education Loan',
    description: 'Collateral-free, guarantor-free loans for students admitted to top-tier higher education institutions in India.',
    category: 'Education',
    level: 'Central',
    ministry: 'Ministry of Education',
    updatedAt: '05 Jan 2025',
    expiryDate: '2028-01-01',
    objectives: ['Financial support for higher ed.', 'No student left behind.'],
    benefits: ['Loans up to ₹7.5 Lakh with 75% credit guarantee.', '3% interest subvention.'],
    eligibility: ['Students in top 860 institutions.', 'Merit based admission.', 'Family income < ₹8 Lakh for subvention.'],
    documents: ['Admission Letter', 'Aadhaar', 'Income Certificate'],
    howToApply: [
      '1. Register on the PM-Vidyalaxmi official portal.',
      '2. Fill out the Common Education Loan Application Form (CELAF).',
      '3. Browse and select loan products from various banks.',
      '4. Upload digital copies of required documents.',
      '5. Submit and track application status through the portal.'
    ],
    applicationUrl: 'https://www.vidyalakshmi.co.in/',
    faqs: [{ question: 'Need guarantor?', answer: 'No.' }]
  },
  {
    id: 'ayushman-senior-70',
    title: 'Ayushman Bharat Senior Citizen (70+) Cover',
    description: 'Universal health insurance cover of ₹5 Lakh per year for every senior citizen aged 70 and above, regardless of income.',
    category: 'Health',
    level: 'Central',
    ministry: 'Ministry of Health and Family Welfare',
    updatedAt: '01 Jan 2025',
    expiryDate: '2030-12-31',
    objectives: ['Provide quality healthcare to the elderly.', 'Reduce medical expense burden.'],
    benefits: ['₹5 Lakh annual health cover.', 'Cashless treatment.', 'Covers pre-existing diseases.'],
    eligibility: ['Indian citizen aged 70 or above.', 'Applicable even if covered under other health schemes.'],
    documents: ['Aadhaar Card (Mandatory for DOB)'],
    howToApply: [
      '1. Open the Ayushman App or visit beneficiary.nha.gov.in.',
      '2. Login with your Aadhaar-linked mobile number.',
      '3. Search for your record using the 70+ Senior Citizen category.',
      '4. Perform e-KYC using biometric or OTP.',
      '5. Download your Ayushman 70+ Card instantly.'
    ],
    applicationUrl: 'https://beneficiary.nha.gov.in/',
    faqs: [{ question: 'Is income limit applicable?', answer: 'No, this expansion is universal for all seniors 70+.' }]
  },
  {
    id: 'pm-kisan-2025',
    title: 'PM-KISAN Samman Nidhi',
    description: 'Direct income support of ₹6,000 per year to landholding farmer families in three equal installments.',
    category: 'Agriculture',
    level: 'Central',
    ministry: 'Ministry of Agriculture',
    updatedAt: '01 Jan 2025',
    expiryDate: '2027-06-30',
    objectives: ['Supplement farmers financial needs.', 'Direct bank transfer.'],
    benefits: ['₹6,000 per year in 3 installments.', 'KCC linkage support.'],
    eligibility: ['All landholding farmer families.', 'Land record must be in applicant name.'],
    documents: ['Land Records', 'Aadhaar Card', 'Bank Passbook'],
    howToApply: [
      '1. Visit pmkisan.gov.in and select "New Farmer Registration".',
      '2. Enter Aadhaar and mobile number for verification.',
      '3. Fill in landholding and bank details accurately.',
      '4. Upload proof of land ownership.',
      '5. Complete Aadhaar e-KYC to start receiving payments.'
    ],
    applicationUrl: 'https://pmkisan.gov.in/',
    faqs: [{ question: 'How often are payments?', answer: 'Every four months (₹2,000 each).' }]
  },
  {
    id: 'pm-vishwakarma',
    title: 'PM Vishwakarma Scheme',
    description: 'Support for artisans and craftspeople using hands and tools in traditional trades.',
    category: 'Employment',
    level: 'Central',
    ministry: 'Ministry of MSME',
    updatedAt: '10 Feb 2025',
    expiryDate: '2027-12-31',
    objectives: ['Recognition as Vishwakarma.', 'Skill training.', 'Toolkit support.'],
    benefits: ['₹15,000 toolkit incentive.', 'Credit up to ₹3L at 5%.', 'Stipend for training.'],
    eligibility: ['Artisans in 18 traditional trades.', 'Aged 18+.', 'Only one per family.'],
    documents: ['Aadhaar', 'Mobile', 'Bank Details', 'Ration Card'],
    howToApply: [
      '1. Visit a nearby Common Service Centre (CSC).',
      '2. Undergo biometric Aadhaar registration.',
      '3. Complete the 3-tier verification (Gram Panchayat/ULB/Dist).',
      '4. Attend basic training (5-7 days) to get your ID card.',
      '5. Apply for toolkit grant and credit support.'
    ],
    applicationUrl: 'https://pmvishwakarma.gov.in/',
    faqs: [{ question: 'Which trades are covered?', answer: '18 trades including carpenters, potters, blacksmiths, etc.' }]
  },
  {
    id: 'sukanya-samriddhi',
    title: 'Sukanya Samriddhi Yojana (SSY)',
    description: 'Savings scheme for girl child education and marriage with high interest rates and tax benefits.',
    category: 'Finance',
    level: 'Central',
    ministry: 'Ministry of Finance',
    updatedAt: '01 Jan 2025',
    expiryDate: '2030-12-31',
    objectives: ['Financial security for girl child.', 'Encourage long-term savings.'],
    benefits: ['Interest rate approx 8.2%.', 'Tax deduction under 80C.', 'Mature after 21 years.'],
    eligibility: ['Girl child below 10 years.', 'Opened by parent/guardian.', 'Limit 2 girls per family.'],
    documents: ['Birth Certificate of girl', 'Aadhaar of guardian'],
    howToApply: [
      '1. Visit your local Post Office or authorized bank.',
      '2. Fill out the SSY account opening form.',
      '3. Provide girl child\'s birth certificate and KYC documents.',
      '4. Deposit minimum initial amount of ₹250.',
      '5. Collect passbook for future tracking.'
    ],
    applicationUrl: 'https://www.indiapost.gov.in/',
    faqs: [{ question: 'Minimum deposit?', answer: '₹250 per year.' }]
  },
  {
    id: 'pm-svanidhi',
    title: 'PM SVANidhi (Street Vendors Loan)',
    description: 'Micro-credit for street vendors to provide affordable working capital loans for business restart.',
    category: 'Business',
    level: 'Central',
    ministry: 'Ministry of Housing and Urban Affairs',
    updatedAt: '20 Dec 2024',
    expiryDate: '2026-12-31',
    objectives: ['Affordable working capital.', 'Promote digital transactions.'],
    benefits: ['Loan of ₹10,000, then ₹20k & ₹50k.', '7% interest subsidy.', 'Digital transaction cashback.'],
    eligibility: ['Street vendors in urban areas.', 'Certificate of Vending holders.'],
    documents: ['Aadhaar', 'Voter ID', 'Certificate of Vending'],
    howToApply: [
      '1. Log on to pmsvanidhi.mohua.gov.in or use the app.',
      '2. Check your name in the Vendor survey list.',
      '3. Apply for the loan selecting a preferred lender.',
      '4. Verification of documents by ULB/Bank.',
      '5. Direct disbursement to your savings account.'
    ],
    applicationUrl: 'https://pmsvanidhi.mohua.gov.in/',
    faqs: [{ question: 'Collateral needed?', answer: 'No, it is collateral-free.' }]
  },
  {
    id: 'atal-pension',
    title: 'Atal Pension Yojana (APY)',
    description: 'Pension scheme for the unorganized sector to ensure post-retirement income.',
    category: 'Finance',
    level: 'Central',
    ministry: 'Ministry of Finance',
    updatedAt: '15 Jan 2025',
    expiryDate: '2035-12-31',
    objectives: ['Social security for workers.', 'Guaranteed monthly pension.'],
    benefits: ['Monthly pension of ₹1k-₹5k.', 'Spouse/Nominee benefits.'],
    eligibility: ['Indian citizen 18-40 years.', 'Savings bank account holder.'],
    documents: ['Aadhaar', 'Bank Account', 'Mobile Number'],
    howToApply: [
      '1. Contact your bank branch or use net banking.',
      '2. Fill the APY registration form.',
      '3. Choose your pension amount (₹1,000 to ₹5,000).',
      '4. Link your account for auto-debit of premiums.',
      '5. Receive your PRAN card through post.'
    ],
    applicationUrl: 'https://npscra.nsdl.co.in/scheme-details.php',
    faqs: [{ question: 'Can I exit early?', answer: 'Only in exceptional cases like death or critical illness.' }]
  },
  {
    id: 'stand-up-india',
    title: 'Stand Up India Scheme',
    description: 'Loans for SC/ST and women entrepreneurs for setting up greenfield enterprises.',
    category: 'Business',
    level: 'Central',
    ministry: 'Ministry of Finance',
    updatedAt: '12 Jan 2025',
    expiryDate: '2028-12-31',
    objectives: ['Promote entrepreneurship among women/SC/ST.', 'Financial inclusion.'],
    benefits: ['Loans between ₹10 Lakh to ₹1 Crore.', 'Composite loan covering 75% of project cost.'],
    eligibility: ['SC/ST or Woman entrepreneur.', 'Aged 18+.', 'Greenfield projects only.'],
    documents: ['Business Plan', 'Category Certificate', 'Identity/Address Proof'],
    howToApply: [
      '1. Visit standupmitra.in portal.',
      '2. Register and select your business category.',
      '3. Fill the loan application form with project details.',
      '4. Choose a bank from the portal list.',
      '5. Bank will verify and process loan for greenfield startup.'
    ],
    applicationUrl: 'https://www.standupmitra.in/',
    faqs: [{ question: 'What is greenfield?', answer: 'A first-time venture in manufacturing/service/trading sectors.' }]
  },
  {
    id: 'pm-matru-vandana',
    title: 'PM Matru Vandana Yojana (PMMVY)',
    description: 'Maternity benefit for pregnant and lactating mothers for the first living child of the family.',
    category: 'Women & Child',
    level: 'Central',
    ministry: 'Ministry of Women and Child Development',
    updatedAt: '01 Feb 2025',
    expiryDate: '2027-12-31',
    objectives: ['Incentivize healthy behavior.', 'Partial compensation for wage loss.'],
    benefits: ['Cash incentive of ₹5,000 in three installments.'],
    eligibility: ['Pregnant and lactating mothers.', 'First living child of family.'],
    documents: ['MCP Card', 'Aadhaar', 'Husband\'s Aadhaar', 'Bank Details'],
    howToApply: [
      '1. Register at your local Anganwadi centre.',
      '2. Submit Form 1-A with required identity proofs.',
      '3. Complete institutional delivery and immunization.',
      '4. Money is credited via DBT to Aadhaar-linked account.',
      '5. Track status via PMMVY-CAS portal.'
    ],
    applicationUrl: 'https://pmmvy-cas.nic.in/',
    faqs: [{ question: 'Is it for government employees?', answer: 'No, they are generally excluded.' }]
  },

  // --- STATE SCHEMES ---
  {
    id: 'ladli-behna-mp',
    title: 'Mukhyamantri Ladli Behna Yojana (MP)',
    description: 'Monthly assistance of ₹1,250 to women in Madhya Pradesh to empower them and improve health.',
    category: 'Women & Child',
    level: 'State',
    ministry: 'Govt of Madhya Pradesh',
    updatedAt: '05 Feb 2025',
    expiryDate: '2028-03-31',
    objectives: ['Economic independence of women.', 'Improve nutrition status.'],
    benefits: ['₹1,250 per month directly to bank account.'],
    eligibility: ['Women residents of MP.', 'Aged 21-60 years.', 'Family income < ₹2.5L.'],
    documents: ['Samagra ID', 'Aadhaar', 'Bank Passbook'],
    howToApply: [
      '1. Attend registration camps at local Panchayat/Ward.',
      '2. Provide Samagra ID and Aadhaar for biometric check.',
      '3. Fill the application form with help of camp officials.',
      '4. Ensure bank account is Aadhaar seeded for DBT.',
      '5. Funds arrive on the 10th of every month.'
    ],
    applicationUrl: 'https://cmladlibehna.mp.gov.in/',
    faqs: [{ question: 'Is it for unmarried women?', answer: 'No, currently married/widowed/divorced.' }]
  },
  {
    id: 'rythu-bandhu-tg',
    title: 'Rythu Bandhu (Telangana)',
    description: 'Investment support scheme for farmers in Telangana to support purchase of seeds and fertilizers.',
    category: 'Agriculture',
    level: 'State',
    ministry: 'Govt of Telangana',
    updatedAt: '12 Jan 2025',
    expiryDate: '2027-12-31',
    objectives: ['Investment support per season.', 'Relieve farm debt.'],
    benefits: ['₹10,000 per acre per year (₹5,000 per season).'],
    eligibility: ['Landholding farmers in Telangana.', 'Pattadar passbook holders.'],
    documents: ['Pattadar Passbook', 'Aadhaar Card', 'Bank Details'],
    howToApply: [
      '1. Ensure land details are updated on Dharani portal.',
      '2. Submit bank and Aadhaar details to Agriculture Extension Officer.',
      '3. Verification is done by Revenue Dept.',
      '4. Money is credited per season through DBT.',
      '5. Check status on official Rythu Bandhu portal.'
    ],
    applicationUrl: 'https://rythubandhu.telangana.gov.in/',
    faqs: [{ question: 'Is tenant farmer eligible?', answer: 'No, only land owners.' }]
  },
  {
    id: 'kanyashree-wb',
    title: 'Kanyashree Prakalpa (West Bengal)',
    description: 'Scholarships for girls in West Bengal to prevent child marriage and encourage education.',
    category: 'Education',
    level: 'State',
    ministry: 'Govt of West Bengal',
    updatedAt: '20 Jan 2025',
    expiryDate: '2030-12-31',
    objectives: ['Stop child marriage.', 'Promote girls\' higher education.'],
    benefits: ['Annual scholarship of ₹1,000 (K1).', 'One-time grant of ₹25,000 (K2).'],
    eligibility: ['Resident girls 13-18 (K1) & 18-19 (K2).', 'Unmarried and enrolled in education.'],
    documents: ['Birth Certificate', 'Aadhaar', 'Unmarried Declaration', 'School ID'],
    howToApply: [
      '1. Obtain the Kanyashree form from your school.',
      '2. Fill personal details and get it signed by Principal.',
      '3. Submit along with identity and age proofs.',
      '4. Institution uploads form to portal.',
      '5. Grant is credited to student\'s bank account.'
    ],
    applicationUrl: 'https://www.wbkanyashree.gov.in/',
    faqs: [{ question: 'What is K2 age?', answer: 'Must be applied when the girl turns 18.' }]
  },
  {
    id: 'gruha-lakshmi-ka',
    title: 'Gruha Lakshmi Scheme (Karnataka)',
    description: 'Monthly support of ₹2,000 to the woman head of household in Karnataka.',
    category: 'Women & Child',
    level: 'State',
    ministry: 'Govt of Karnataka',
    updatedAt: '18 Jan 2025',
    expiryDate: '2028-05-31',
    objectives: ['Mitigate inflation impact.', 'Support female family heads.'],
    benefits: ['₹2,000 monthly cash assistance.'],
    eligibility: ['Resident women head of families.', 'Ration card holder (BPL/APL).'],
    documents: ['Ration Card', 'Aadhaar of Self & Spouse', 'Bank Details'],
    howToApply: [
      '1. Register on Seva Sindhu portal or Karnataka One.',
      '2. Submit your Ration Card number to find family head.',
      '3. Link your bank account with Aadhaar for DBT.',
      '4. Visit nearest Gram One center for biometric verification.',
      '5. Check status using SMS alerts.'
    ],
    applicationUrl: 'https://sevasindhu.karnataka.gov.in/',
    faqs: [{ question: 'Tax payers eligible?', answer: 'No, GST or Income Tax payers excluded.' }]
  },
  {
    id: 'kanya-sumangala-up',
    title: 'Mukhyamantri Kanya Sumangala Yojana (UP)',
    description: 'Financial aid for girls in UP at 6 different stages from birth to graduation.',
    category: 'Women & Child',
    level: 'State',
    ministry: 'Govt of Uttar Pradesh',
    updatedAt: '10 Feb 2025',
    expiryDate: '2029-03-31',
    objectives: ['Curb female foeticide.', 'Support girls\' education.'],
    benefits: ['Total grant up to ₹25,000 in stages.'],
    eligibility: ['Resident of UP.', 'Family income < ₹3 Lakh.', 'Max 2 girls per family.'],
    documents: ['Birth Certificate', 'Aadhaar', 'Income Certificate', 'Affidavit'],
    howToApply: [
      '1. Register on the Kanya Sumangala portal.',
      '2. Apply for the specific stage (e.g., Birth, Admission).',
      '3. Upload certificates corresponding to the stage.',
      '4. Verification by District Probation Officer.',
      '5. Amount is transferred to parent\'s bank account.'
    ],
    applicationUrl: 'https://mksy.up.gov.in/',
    faqs: [{ question: 'Stage 1 grant?', answer: '₹2,000 on birth.' }]
  },
  {
    id: 'jyotirao-phule-mh',
    title: 'Jyotirao Phule Jan Arogya Yojana (Maharashtra)',
    description: 'Health insurance for poor families in Maharashtra covering 996 medical procedures.',
    category: 'Health',
    level: 'State',
    ministry: 'Govt of Maharashtra',
    updatedAt: '05 Jan 2025',
    expiryDate: '2030-12-31',
    objectives: ['Health cover for low income.', 'Cashless treatment.'],
    benefits: ['Cover up to ₹1.5 Lakh per year.', 'Free diagnostics and meds.'],
    eligibility: ['Ration card holders (Yellow/Orange) in MH.', 'Distressed farmers.'],
    documents: ['Ration Card', 'Aadhaar', 'Health Records'],
    howToApply: [
      '1. Visit any empanelled hospital in Maharashtra.',
      '2. Meet the "Arogyamitra" at the helpdesk.',
      '3. Present Ration card and Aadhaar for eligibility check.',
      '4. Hospital seeks pre-authorization from the trust.',
      '5. Get cashless treatment after approval.'
    ],
    applicationUrl: 'https://www.jeevandayee.gov.in/',
    faqs: [{ question: 'Renal transplant cover?', answer: 'Higher cover up to ₹2.5 Lakh.' }]
  },
  {
    id: 'bihar-student-credit',
    title: 'Bihar Student Credit Card (MNSSBY)',
    description: 'Education loan up to ₹4 Lakh for higher studies after 12th standard for Bihar students.',
    category: 'Education',
    level: 'State',
    ministry: 'Govt of Bihar',
    updatedAt: '15 Jan 2025',
    expiryDate: '2028-12-31',
    objectives: ['Higher Gross Enrollment Ratio.', 'Low interest funding.'],
    benefits: ['Loan up to ₹4 Lakh.', '1% interest for girls, 4% for boys.'],
    eligibility: ['Bihar resident.', 'Aged below 25.', 'Passed 12th grade.'],
    documents: ['12th Marksheet', 'Admission Proof', 'Residence Certificate'],
    howToApply: [
      '1. Register on MNSSBY portal of Bihar govt.',
      '2. Fill application and book slot for DRCC visit.',
      '3. Visit District Registration and Counseling Centre (DRCC).',
      '4. Physically verify your original documents.',
      '5. Receive the card for fee payment to your college.'
    ],
    applicationUrl: 'https://www.7nishchay-yuvaupmission.bihar.gov.in/',
    faqs: [{ question: 'Repayment period?', answer: 'Starts after completion of course + 1 year.' }]
  },
  {
    id: 'amma-vodi-ap',
    title: 'Jagananna Amma Vodi (Andhra Pradesh)',
    description: 'Annual grant of ₹15,000 to mothers for sending children to school in Andhra Pradesh.',
    category: 'Education',
    level: 'State',
    ministry: 'Govt of Andhra Pradesh',
    updatedAt: '01 Jan 2025',
    expiryDate: '2027-06-30',
    objectives: ['Ensure school enrollment.', 'Support mothers\' finances.'],
    benefits: ['₹15,000 per year directly to mother\'s account.'],
    eligibility: ['Resident of AP.', 'Children in classes 1-12.', '75% attendance mandatory.'],
    documents: ['Aadhaar', 'White Ration Card', 'Attendance Record'],
    howToApply: [
      '1. Ensure child is enrolled in a recognized school in AP.',
      '2. School uploads student data to education portal.',
      '3. Verify your name in the social audit list at the Secretariat.',
      '4. Link mother\'s bank account with Aadhaar.',
      '5. Amount is credited on the launch date annually.'
    ],
    applicationUrl: 'https://jaganannaammavodi.ap.gov.in/',
    faqs: [{ question: 'Only for Govt schools?', answer: 'No, applicable to private schools too.' }]
  },
  {
    id: 'kalie-odisha',
    title: 'KALIA Scheme (Odisha)',
    description: 'Support for farmers, landless workers, and sharecroppers in Odisha for agricultural livelihoods.',
    category: 'Agriculture',
    level: 'State',
    ministry: 'Govt of Odisha',
    updatedAt: '10 Feb 2025',
    expiryDate: '2027-12-31',
    objectives: ['Income support for cultivators.', 'Livelihood support for landless.'],
    benefits: ['₹10,000 per family per year.', 'Interest-free crop loans up to ₹1L.'],
    eligibility: ['Small/Marginal farmers or landless laborers in Odisha.', 'Sharecroppers.'],
    documents: ['Land Records', 'Aadhaar', 'Bank Passbook'],
    howToApply: [
      '1. Visit the KALIA portal for online registration.',
      '2. Enter Aadhaar number to check existing status.',
      '3. Fill personal and landholding/livelihood details.',
      '4. Complete e-KYC on the portal.',
      '5. Money is transferred directly via DBT.'
    ],
    applicationUrl: 'https://kalia.odisha.gov.in/',
    faqs: [{ question: 'Is it for large farmers?', answer: 'No, focused on small and marginal farmers.' }]
  },
  {
    id: 'yuva-nidhi-ka',
    title: 'Yuva Nidhi (Karnataka)',
    description: 'Unemployment allowance for graduates and diploma holders in Karnataka to support job search.',
    category: 'Employment',
    level: 'State',
    ministry: 'Govt of Karnataka',
    updatedAt: '01 Jan 2025',
    expiryDate: '2028-12-31',
    objectives: ['Financial aid for unemployed youth.', 'Promote skill development.'],
    benefits: ['₹3,000 for Graduates, ₹1,500 for Diploma holders.', 'Paid for up to 2 years.'],
    eligibility: ['Karnataka resident youth.', 'Graduated/Diploma in last 2 years.', 'Unemployed for min 6 months.'],
    documents: ['Degree/Diploma Certificate', 'Aadhaar', 'Residence Proof'],
    howToApply: [
      '1. Apply through the Seva Sindhu portal.',
      '2. Submit education details and passing year.',
      '3. Self-declare unemployment status monthly.',
      '4. Link your Aadhaar with bank account for payment.',
      '5. Complete annual self-declaration to continue benefits.'
    ],
    applicationUrl: 'https://sevasindhu.karnataka.gov.in/',
    faqs: [{ question: 'Is there an age limit?', answer: 'Typically for youth under 30.' }]
  },
  {
    id: 'pmegp',
    title: 'Prime Minister Employment Generation Programme (PMEGP)',
    description: 'Credit linked subsidy scheme for setting up new micro-enterprises in non-farm sectors.',
    category: 'Business',
    level: 'Central',
    ministry: 'Ministry of MSME',
    updatedAt: '15 Jan 2025',
    expiryDate: '2027-03-31',
    objectives: ['Generate employment in rural/urban areas.', 'Support new startups.'],
    benefits: ['Subsidy of 15-35% of project cost.', 'Loans up to ₹50 Lakh for manufacturing.'],
    eligibility: ['Aged 18+.', 'At least 8th pass for large projects.', 'Self Help Groups.'],
    documents: ['Project Report', 'Aadhaar', 'Education Proof', 'Category Certificate'],
    howToApply: [
      '1. Apply online via KVIC PMEGP portal.',
      '2. Choose your implementing agency (KVIC/KVIB/DIC).',
      '3. Upload your project report and identity documents.',
      '4. Agency forwards your proposal to the bank.',
      '5. Bank sanctions the loan and you receive the margin money (subsidy).'
    ],
    applicationUrl: 'https://www.kviconline.gov.in/pmegpeportal/',
    faqs: [{ question: 'Is it for existing business?', answer: 'No, only for new greenfield units.' }]
  },
  {
    id: 'pm-kushal-vikas',
    title: 'PM Kaushal Vikas Yojana (PMKVY)',
    description: 'Skill certification scheme aimed at enabling Indian youth to take up industry-relevant skill training.',
    category: 'Employment',
    level: 'Central',
    ministry: 'Ministry of Skill Development',
    updatedAt: '20 Dec 2024',
    expiryDate: '2026-12-31',
    objectives: ['Standardized skill training.', 'Improve employability of youth.'],
    benefits: ['Free skill training.', 'NSDC certification.', 'Placement assistance.'],
    eligibility: ['Unemployed youth or school/college dropouts.', 'Indian nationality.'],
    documents: ['Aadhaar', 'Voter ID', 'Education Marksheet'],
    howToApply: [
      '1. Visit the Skill India Digital portal.',
      '2. Search for a training center and course in your area.',
      '3. Register and provide your basic details.',
      '4. Complete the training and pass the assessment.',
      '5. Receive your certificate and reward through DBT if applicable.'
    ],
    applicationUrl: 'https://www.skillindiadigital.gov.in/',
    faqs: [{ question: 'Is training free?', answer: 'Yes, fully funded by the government.' }]
  },
  {
    id: 'stand-up-business',
    title: 'Mudra Shishu Loan (₹50k)',
    description: 'Immediate micro-credit for tiny businesses and startups with minimal documentation.',
    category: 'Business',
    level: 'Central',
    ministry: 'Ministry of Finance',
    updatedAt: '01 Feb 2025',
    expiryDate: '2030-12-31',
    objectives: ['Fast funding for micro units.', 'Promote small vendors.'],
    benefits: ['Loan up to ₹50,000.', 'No processing fee.', 'Low interest rate.'],
    eligibility: ['Small retailers, vendors, artisans.', 'New or existing micro-enterprises.'],
    documents: ['KYC (Aadhaar/PAN)', 'Business Address Proof', 'Bank statement (if any)'],
    howToApply: [
      '1. Approach any Bank or MFI branch.',
      '2. Fill the Shishu Mudra application form (1 page).',
      '3. Submit your identity and business location proof.',
      '4. Bank conducts a quick verification visit.',
      '5. Amount is credited within 7-10 working days.'
    ],
    applicationUrl: 'https://www.mudra.org.in/',
    faqs: [{ question: 'Need collateral?', answer: 'No collateral required.' }]
  },
  {
    id: 'pm-awas-rural',
    title: 'PMAY-G (Rural Housing)',
    description: 'Financial assistance for construction of pucca houses for rural homeless families.',
    category: 'Housing',
    level: 'Central',
    ministry: 'Ministry of Rural Development',
    updatedAt: '10 Jan 2025',
    expiryDate: '2027-12-31',
    objectives: ['Housing for all in rural areas.', 'Replace kucha houses.'],
    benefits: ['Grant of ₹1.2 Lakh to ₹1.3 Lakh.', 'Extra ₹95k for labor under MGNREGA.'],
    eligibility: ['Rural families in SECC 2011 list.', 'Homeless or living in kucha house.'],
    documents: ['Aadhaar', 'Bank Details', 'MGNREGA Job Card'],
    howToApply: [
      '1. Beneficiary selection is done via Gram Sabha based on SECC data.',
      '2. Register details on AwaasSoft portal with help of BDO office.',
      '3. Geotagging of the old house is done.',
      '4. First installment is released for foundation.',
      '5. Subsequent installments released based on construction progress photos.'
    ],
    applicationUrl: 'https://pmayg.nic.in/',
    faqs: [{ question: 'Can I apply directly?', answer: 'Selection is generally through the pre-verified list.' }]
  }
];
